/**
 * Micro-Tools admin — per-section field configs.
 *
 * Each section maps to a /api/tools/<endpoint>/ resource. `fields` drives both
 * the table columns (those with list:true) and the create/edit form.
 * Field types: text | textarea | number | select | date | switch | file | image
 * Optional per-field `help`: shown under the input to explain what to enter.
 * Optional per-section `note`: what the section is + how it appears in the app.
 */

const COURT_OPTIONS = [
  { value: 'supreme', label: 'Supreme Court' },
  { value: 'high', label: 'High Court' },
  { value: 'district', label: 'District Court' },
];

// Appended to every section.
const COMMON_FIELDS = [
  { name: 'display_order', label: 'Order', type: 'number', default: 0, list: true, width: 80,
    help: 'Lower numbers appear first in the app. Leave 0 if order does not matter.' },
  { name: 'is_active', label: 'Active', type: 'switch', default: true, list: true, width: 90,
    help: 'Off = hidden from the app but kept here as a draft.' },
];

export const SECTIONS = {
  judges: {
    title: 'Judges',
    endpoint: 'judges',
    description: 'High Court & District Court judges',
    icon: 'gavel',
    color: '#d46b08',
    note: 'Each entry is one judge, shown in the app as a card under High Court / District Courts (grouped by the Court field). Card shows the photo, name, designation and court; a "Link" button appears if you add a video-hearing URL.',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, list: true,
        help: 'Full name as it should appear, e.g. "Hon\'ble Justice A. K. Sharma".' },
      { name: 'court', label: 'Court', type: 'select', options: COURT_OPTIONS, required: true, default: 'high', list: true,
        help: 'Which court list this judge appears under in the app.' },
      { name: 'designation', label: 'Designation', type: 'text', list: true,
        help: 'Role/title, e.g. "Chief Justice", "District Judge". Shown as the subtitle.' },
      { name: 'court_name', label: 'Court name', type: 'text',
        help: 'Specific court, e.g. "Delhi High Court", "Tis Hazari Court".' },
      { name: 'court_room', label: 'Court room', type: 'text',
        help: 'Court/room number if known, e.g. "Court No. 12".' },
      { name: 'link_url', label: 'Video-hearing link', type: 'text', placeholder: 'https://...',
        help: 'Optional Webex/virtual-court URL. Adds a tappable "Link" button on the card.' },
      { name: 'photo', label: 'Photo', type: 'image',
        help: 'Optional headshot. Shown as a round avatar; a default icon is used if empty.' },
      { name: 'state', label: 'State', type: 'text', default: 'Delhi',
        help: 'Jurisdiction. Keep "Delhi" for now.' },
    ],
  },
  bar: {
    title: 'Bar Associations',
    endpoint: 'bar-associations',
    description: 'Association directory with office bearers',
    icon: 'team',
    color: '#531dab',
    note: 'Each entry is one bar association, shown as a directory card with the president/secretary, address and Call/Email buttons (buttons appear only when you fill contact number / email).',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, list: true,
        help: 'Association name, e.g. "Delhi High Court Bar Association".' },
      { name: 'president_name', label: 'President', type: 'text', list: true,
        help: 'Current president. Shown as "President: …".' },
      { name: 'secretary_name', label: 'Secretary', type: 'text',
        help: 'Current secretary. Shown as "Secretary: …".' },
      { name: 'contact_number', label: 'Contact number', type: 'text', list: true,
        help: 'Phone shown as a "Call" button. Digits only, e.g. 9811xxxxxx.' },
      { name: 'email', label: 'Email', type: 'text',
        help: 'Shown as an "Email" button.' },
      { name: 'address', label: 'Address', type: 'textarea',
        help: 'Office address, shown under the name.' },
      { name: 'city', label: 'City', type: 'text', default: 'Delhi' },
      { name: 'state', label: 'State', type: 'text', default: 'Delhi' },
    ],
  },
  police: {
    title: 'Police',
    endpoint: 'police',
    description: 'Administration officers & police stations',
    icon: 'safety',
    color: '#096dd9',
    note: 'Each entry is one officer or police station. The Type field puts it under "Administration" or "Police Station". Card shows name, designation, address and a Call button if a number is given.',
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true, list: true, placeholder: 'Officer or station name',
        help: 'Officer name (e.g. "DCP South") or station name (e.g. "Hauz Khas PS").' },
      { name: 'kind', label: 'Type', type: 'select', required: true, default: 'station', list: true,
        options: [{ value: 'administration', label: 'Administration' }, { value: 'station', label: 'Police Station' }],
        help: 'Administration = senior officers; Police Station = a thana.' },
      { name: 'designation', label: 'Designation', type: 'text', list: true,
        help: 'Rank/role, e.g. "Deputy Commissioner". Shown as subtitle.' },
      { name: 'contact_number', label: 'Contact number', type: 'text',
        help: 'Phone shown as a "Call" button.' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'address', label: 'Address', type: 'textarea',
        help: 'Station/office address.' },
      { name: 'district', label: 'District', type: 'text',
        help: 'e.g. "South", "New Delhi".' },
      { name: 'city', label: 'City', type: 'text', default: 'Delhi' },
      { name: 'state', label: 'State', type: 'text', default: 'Delhi' },
    ],
  },
  rosters: {
    title: 'Rosters',
    endpoint: 'rosters',
    description: 'Bail & duty-magistrate rosters',
    icon: 'schedule',
    color: '#d4380d',
    note: 'Each entry is one roster. Add the details as text and/or attach a PDF — the app shows the title with a "Download" button when a file is attached.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, list: true,
        help: 'e.g. "Bail Roster — July 2026".' },
      { name: 'kind', label: 'Type', type: 'select', required: true, default: 'bail', list: true,
        options: [{ value: 'bail', label: 'Bail Roster' }, { value: 'duty_magistrate', label: 'Duty Magistrate Roster' }],
        help: 'Which kind of roster this is.' },
      { name: 'court', label: 'Court', type: 'select', options: COURT_OPTIONS, default: 'high' },
      { name: 'content', label: 'Roster text', type: 'textarea', rows: 5, placeholder: 'Optional — paste the roster table/text',
        help: 'Optional. Paste the roster if you are not attaching a PDF.' },
      { name: 'file', label: 'File (PDF)', type: 'file', list: true,
        help: 'Attach the official PDF; the app shows a Download button.' },
      { name: 'effective_from', label: 'Effective from', type: 'date' },
      { name: 'effective_to', label: 'Effective to', type: 'date' },
      { name: 'state', label: 'State', type: 'text', default: 'Delhi' },
    ],
  },
  notices: {
    title: 'Notices & Events',
    endpoint: 'notices',
    description: 'Announcements and upcoming events',
    icon: 'notification',
    color: '#d48806',
    note: 'Each entry is one announcement (Notice) or an Event. Shown as a card with title, description, date and an optional Link button.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, list: true,
        help: 'Short headline of the notice/event.' },
      { name: 'kind', label: 'Type', type: 'select', required: true, default: 'notice', list: true,
        options: [{ value: 'notice', label: 'Notice' }, { value: 'event', label: 'Event' }],
        help: 'Notice = announcement; Event = something on a date (appears under Events).' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 4,
        help: 'Body text shown under the title.' },
      { name: 'date', label: 'Date', type: 'date', list: true,
        help: 'Date of the notice/event.' },
      { name: 'link_url', label: 'Link', type: 'text', placeholder: 'https://...',
        help: 'Optional URL — adds a Link button.' },
    ],
  },
  calendar: {
    title: 'Court Calendar',
    endpoint: 'court-calendar',
    description: 'Vacations, holidays & calendar entries',
    icon: 'calendar',
    color: '#389e0d',
    note: 'Each entry is one calendar item (holiday, vacation period, or a calendar image). Shown with title, dates and an optional image the user can open.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, list: true,
        help: 'e.g. "Summer Vacation", "Republic Day (Holiday)".' },
      { name: 'court', label: 'Court', type: 'select', options: COURT_OPTIONS, default: 'high' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3 },
      { name: 'start_date', label: 'Start date', type: 'date', list: true,
        help: 'First day. For a single holiday, use the same start and end date.' },
      { name: 'end_date', label: 'End date', type: 'date' },
      { name: 'year', label: 'Year', type: 'number', help: 'e.g. 2026. Helps filter by year.' },
      { name: 'image', label: 'Image', type: 'image',
        help: 'Optional calendar image; the app lets users open it.' },
      { name: 'state', label: 'State', type: 'text', default: 'Delhi' },
    ],
  },
  forms: {
    title: 'Misc. Forms',
    endpoint: 'form-templates',
    description: 'Downloadable form & document templates',
    icon: 'file',
    color: '#1d39c4',
    note: 'Each entry is one downloadable template. Shown with title, category and a Download button — a file is required.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, list: true,
        help: 'e.g. "Vakalatnama", "Bail Application Format".' },
      { name: 'category', label: 'Category', type: 'text', list: true,
        help: 'Group name, e.g. "Civil", "Criminal". Optional.' },
      { name: 'description', label: 'Description', type: 'textarea', rows: 3 },
      { name: 'file', label: 'File', type: 'file', required: true, list: true,
        help: 'The document to offer for download (PDF/DOC).' },
    ],
  },
  banners: {
    title: 'Banners',
    endpoint: 'banners',
    description: 'Home-screen slider images',
    icon: 'picture',
    color: '#c41d7f',
    note: 'Each entry is one home-screen banner image. Optionally opens a link when tapped. An image is required.',
    fields: [
      { name: 'title', label: 'Title', type: 'text', list: true,
        help: 'Internal label (may be shown as caption).' },
      { name: 'image', label: 'Image', type: 'image', required: true,
        help: 'Wide banner image. Required.' },
      { name: 'link_url', label: 'Link', type: 'text', placeholder: 'https://...',
        help: 'Optional URL opened when the banner is tapped.' },
    ],
  },
};

// Merge common fields once.
Object.values(SECTIONS).forEach((s) => { s.fields = [...s.fields, ...COMMON_FIELDS]; });

export const SECTION_ORDER = ['judges', 'bar', 'police', 'rosters', 'notices', 'calendar', 'forms', 'banners'];
